### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by autonomousapps** [jjohannes/idiomatic-gradle#2]
First, thanks for this very interesting example! I decided to clone it so I could take a look more easily than on Github, and the project won't sync in IDEA, and can't be built as-is from the command line. I simply ran `./gradlew help` and got this error:

```
> Task :buildlogic-packaging:compileKotlin FAILED
The `kotlin-dsl` plugin applied to project ':buildlogic-packaging' enables experimental Kotlin compiler features. For more information see https://docs.gradle.org/6.7-20200723220251+0000/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin
e: /Users/trobalik/workspace/personal/idiomatic-gradle/buildlogic/buildlogic-packaging/src/main/kotlin/buildlogic/packaging.gradle.kts: (47, 31): Unresolved reference: asIterator
e: /Users/trobalik/workspace/personal/idiomatic-gradle/buildlogic/buildlogic-packaging/src/main/kotlin/buildlogic/packaging.gradle.kts: (47, 44): Overload resolution ambiguity:
public inline fun <T> Iterable<TypeVariable(T)>.forEach(action: (TypeVariable(T)) -> Unit): Unit defined in kotlin.collections
public inline fun <K, V> Map<out TypeVariable(K), TypeVariable(V)>.forEach(action: (Map.Entry<TypeVariable(K), TypeVariable(V)>) -> Unit): Unit defined in kotlin.collections
e: /Users/trobalik/workspace/personal/idiomatic-gradle/buildlogic/buildlogic-packaging/src/main/kotlin/buildlogic/packaging.gradle.kts: (49, 35): Unresolved reference: isDirectory
e: /Users/trobalik/workspace/personal/idiomatic-gradle/buildlogic/buildlogic-packaging/src/main/kotlin/buildlogic/packaging.gradle.kts: (50, 69): Unresolved reference: name
```

**Comment by jjohannes** [comment]
Thanks for noticing. I updated to the lates `6.8` nightly and did some more tweaks following recent discussions.

Note that this repo is still an experiment. Things may change in the weeks to come. It also uses some new APIs planned for 6.8, which are still subject to change, to setup "variant-aware" dependencies between projects.

Feedback is of course welcome!

**Comment by martinbonnin** [comment]
@jjohannes looks like latest `6.8` does not fix the issue. I'm at commit `6122c1d8aae51db44433c382c052fd659448fe00` (that uses `gradle-6.8-20200913220037+0000`) and have the same errors

**Comment by jjohannes** [comment]
Ha. I guess you are both using JDK 8. I am using 11 and thus did not realise that I unintentionally used Java APIs not available in 8 (instead of the Kotlin equivalent). Should work now.

**Comment by martinbonnin** [comment]
Yup, good catch, all working now 👍
